# -*- coding: utf-8 -*-
"""BD_AmazonReviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGOs74xXho_Qyovy_jTeCVvUjhiN1OJq

# Install and Import Libraries
"""

# تثبيت PySpark في Google Colab
!pip install pyspark -q

# استيراد SparkSession لإنشاء بيئة Spark
from pyspark.sql import SparkSession

# استيراد دوال PySpark للتنظيف والتحليل
from pyspark.sql.functions import col, count, mean, length, lower, regexp_replace, when, round

# إنشاء Spark Session
spark = SparkSession.builder \
    .appName("AmazonFakeReviewsDetection") \
    .getOrCreate()

# عرض معلومات Spark للتأكد أنه اشتغل
spark

from google.colab import drive

# ربط Google Drive مع Colab
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Colab Notebooks/final_labeled_fake_reviews.csv"

df = spark.read.option("header", True) \
    .option("inferSchema", True) \
    .option("multiLine", True) \
    .option("quote", '"') \
    .option("escape", '"') \
    .csv(path)

df.show(5, truncate=False)
df.printSchema()

print("Rows:", df.count())
print("Columns:", len(df.columns))

# Check Label Values
# نتأكد من قيم عمود label قبل التنظيف

df.groupBy("label").count().orderBy("count", ascending=False).show(20, truncate=False)

import matplotlib.pyplot as plt

# تحويل البيانات إلى pandas
label_counts = df.groupBy("label").count().toPandas()

# رسم Bar Chart
plt.figure()
plt.bar(label_counts['label'], label_counts['count'])
plt.xlabel("Label (0 = Real, 1 = Fake)")
plt.ylabel("Count")
plt.title("Distribution of Real vs Fake Reviews")

# حفظ الصورة
plt.savefig("label_dist.png")

# عرضها
plt.show()

"""# Data Cleaning"""

# Select Important Columns + Clean Data
# اختيار الأعمدة المهمة وتنظيف البيانات


from pyspark.sql.functions import col, length, concat_ws

# اختيار الأعمدة التي نحتاجها للمشروع
df_clean = df.select(
    "rating",
    "title",
    "text",
    "helpful_vote",
    "verified_purchase",
    "label"
)

# حذف الصفوف التي فيها قيم فارغة في الأعمدة الأساسية
df_clean = df_clean.dropna(subset=["rating", "text", "label"])

# دمج العنوان مع نص المراجعة في عمود واحد
df_clean = df_clean.withColumn(
    "review_text",
    concat_ws(" ", col("title"), col("text"))
)

# حساب طول المراجعة
df_clean = df_clean.withColumn(
    "review_length",
    length(col("review_text"))
)

# تحويل label إلى double عشان Spark ML
df_clean = df_clean.withColumn("label", col("label").cast("double"))

# عرض النتيجة
df_clean.select(
    "rating", "review_text", "review_length",
    "helpful_vote", "verified_purchase", "label"
).show(5, truncate=False)

print("Rows after cleaning:", df_clean.count())

"""# Basic EDA - Descriptive Statistics"""

# إحصائيات وصفية للأعمدة الرقمية

numerical_cols = ["rating", "helpful_vote", "review_length"]

df_clean.select(*numerical_cols).describe().show()

# توزيع التصنيفات Fake / Real
print("Label Distribution:")
df_clean.groupBy("label").count().show()

# توزيع الشراء الموثق
print("Verified Purchase Distribution:")
df_clean.groupBy("verified_purchase").count().show()

# Compare Fake vs Real Reviews
# مقارنة المراجعات الحقيقية والمزيفة

from pyspark.sql.functions import mean, count, round

df_clean.groupBy("label").agg(
    count("*").alias("total_reviews"),
    round(mean("rating"), 2).alias("avg_rating"),
    round(mean("helpful_vote"), 2).alias("avg_helpful_votes"),
    round(mean("review_length"), 2).alias("avg_review_length")
).show()

"""# Correlation Analysis"""

# Correlation Analysis
# تحليل الارتباط بين الخصائص الرقمية

from pyspark.ml.stat import Correlation
from pyspark.ml.feature import VectorAssembler
import pandas as pd

# الأعمدة الرقمية
corr_cols = ["rating", "helpful_vote", "review_length", "label"]

# تجميع الأعمدة الرقمية في vector
assembler = VectorAssembler(
    inputCols=corr_cols,
    outputCol="corr_features",
    handleInvalid="skip"
)

df_corr_vector = assembler.transform(df_clean).select("corr_features")

# حساب Pearson Correlation
pearson_matrix = Correlation.corr(df_corr_vector, "corr_features", "pearson").head()[0]

# تحويلها إلى جدول واضح
corr_array = pearson_matrix.toArray()
corr_df = pd.DataFrame(corr_array, index=corr_cols, columns=corr_cols)

print("Pearson Correlation Matrix:")
print(corr_df.round(3))

# Heatmap Visualization

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.heatmap(corr_df, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap: Amazon Fake Reviews")
plt.show()

"""# Drill-Down Analysis"""

# تحليل تفصيلي حسب verified_purchase و rating

from pyspark.sql.functions import mean, count, round

drill_down_df = df_clean.rollup("verified_purchase", "rating").agg(
    count("*").alias("total_reviews"),
    round(mean("helpful_vote"), 2).alias("avg_helpful_votes"),
    round(mean("review_length"), 2).alias("avg_review_length"),
    round(mean("label"), 2).alias("fake_ratio")
).orderBy("verified_purchase", "rating")

drill_down_df.show(30, truncate=False)

"""# Cohort Comparison

"""

# مقارنة Fake Reviews مع Real Reviews

from pyspark.sql.functions import lit

real_reviews = df_clean.filter(col("label") == 0)
fake_reviews = df_clean.filter(col("label") == 1)

compare_cols = ["rating", "helpful_vote", "review_length"]

compare_exprs = [
    round(mean(c), 2).alias(f"avg_{c}") for c in compare_cols
]

real_metrics = real_reviews.agg(*compare_exprs).withColumn("cohort", lit("Real Reviews"))
fake_metrics = fake_reviews.agg(*compare_exprs).withColumn("cohort", lit("Fake Reviews"))

comparison_df = real_metrics.unionByName(fake_metrics)

cols = ["cohort"] + [c for c in comparison_df.columns if c != "cohort"]
comparison_df.select(cols).show()

"""# NLP Text Processing Pipeline"""

# تحويل نصوص المراجعات إلى features

from pyspark.ml.feature import Tokenizer, StopWordsRemover, HashingTF, IDF, VectorAssembler
from pyspark.ml import Pipeline

# 1) Tokenizer: تقسيم النص إلى كلمات
tokenizer = Tokenizer(
    inputCol="review_text",
    outputCol="words")

# 2) StopWordsRemover: حذف الكلمات غير المهمة مثل the, is, and
remover = StopWordsRemover(
    inputCol="words",
    outputCol="filtered_words")

# 3) HashingTF: تحويل الكلمات إلى أرقام
hashingTF = HashingTF(
    inputCol="filtered_words",
    outputCol="tf_features",
    numFeatures=10000)

# 4) IDF: إعطاء وزن أعلى للكلمات المهمة
idf = IDF(
    inputCol="tf_features",
    outputCol="text_features")

# 5) VectorAssembler: دمج خصائص النص مع الخصائص الرقمية
assembler = VectorAssembler(
    inputCols=["text_features", "rating", "helpful_vote", "review_length"],
    outputCol="features")

# بناء Pipeline كامل
nlp_pipeline = Pipeline(stages=[
    tokenizer,
    remover,
    hashingTF,
    idf,
    assembler])

# تدريب Pipeline وتحويل البيانات
pipeline_model = nlp_pipeline.fit(df_clean)
data = pipeline_model.transform(df_clean)

# عرض الأعمدة المهمة بعد التحويل
data.select("review_text", "filtered_words", "features", "label").show(5, truncate=False)

# Train/Test Split
# تقسيم البيانات إلى تدريب واختبار

train_data, test_data = data.randomSplit([0.8, 0.2], seed=42)

print("Training rows:", train_data.count())
print("Testing rows:", test_data.count())

"""# Supervised Learning - Logistic Regression"""

# نموذج تصنيف للتنبؤ بالمراجعات المزيفة

from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# إنشاء النموذج
lr = LogisticRegression(
    featuresCol="features",
    labelCol="label",
    maxIter=20
)

# تدريب النموذج
lr_model = lr.fit(train_data)

# التنبؤ على بيانات الاختبار
lr_predictions = lr_model.transform(test_data)

# عرض النتائج
lr_predictions.select(
    "review_text", "label", "prediction", "probability"
).show(5, truncate=False)

# تقييم النموذج
accuracy_evaluator = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="accuracy"
)

f1_evaluator = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="f1"
)

accuracy = accuracy_evaluator.evaluate(lr_predictions)
f1_score = f1_evaluator.evaluate(lr_predictions)

# استخدام Python's built-in round function for float values
print("Logistic Regression Accuracy:", __builtins__.round(accuracy, 4))
print("Logistic Regression F1-score:", __builtins__.round(f1_score, 4))

"""# Supervised Learning - Decision Tree"""

from pyspark.ml.classification import DecisionTreeClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# إنشاء نموذج Decision Tree
dt = DecisionTreeClassifier(
    labelCol="label",
    featuresCol="features",
    maxDepth=10
)

# تدريب النموذج
dt_model = dt.fit(train_data)

# التنبؤ على بيانات الاختبار
dt_predictions = dt_model.transform(test_data)

# تقييم النموذج
dt_accuracy = accuracy_evaluator.evaluate(dt_predictions)
dt_f1 = f1_evaluator.evaluate(dt_predictions)

print("Decision Tree Accuracy:", __builtins__.round(dt_accuracy, 4))
print("Decision Tree F1-score:", __builtins__.round(dt_f1, 4))

"""# Supervised Learning - Naive Bayes"""

# مناسب جدًا مع النصوص

from pyspark.ml.classification import NaiveBayes

# Naive Bayes يحتاج features غير سالبة، وخصائصنا هنا مناسبة لأنها TF-IDF + أرقام موجبة
nb = NaiveBayes(
    labelCol="label",
    featuresCol="features",
    modelType="multinomial"
)

# تدريب النموذج
nb_model = nb.fit(train_data)

# التنبؤ
nb_predictions = nb_model.transform(test_data)

# التقييم
nb_accuracy = accuracy_evaluator.evaluate(nb_predictions)
nb_f1 = f1_evaluator.evaluate(nb_predictions)

print("Naive Bayes Accuracy:",  __builtins__.round(nb_accuracy, 4))
print("Naive Bayes F1-score:",  __builtins__.round(nb_f1, 4))

# Compare Model Results
# مقارنة نتائج النماذج

results = [
    ("Logistic Regression", accuracy, f1_score),
    ("Decision Tree", dt_accuracy, dt_f1),
    ("Naive Bayes", nb_accuracy, nb_f1)
]

results_df = spark.createDataFrame(
    results,
    ["Model", "Accuracy", "F1_score"]
)

results_df.show(truncate=False)

import matplotlib.pyplot as plt

# Only include models that have been run and their accuracy values defined
models = ["Logistic Regression", "Decision Tree", "Naive Bayes"]
accuracy_values = [accuracy, dt_accuracy, nb_accuracy]

plt.figure()
plt.bar(models, accuracy_values)
plt.xticks(rotation=30)
plt.ylabel("Accuracy")
plt.title("Model Comparison (LR, DT, NB only)")

plt.savefig("model_comparison.png")
plt.show()

"""# Unsupervised Learning - K-Means Clustering"""

# اكتشاف أنماط بدون استخدام label

from pyspark.ml.clustering import KMeans

# إنشاء K-Means
kmeans = KMeans(
    k=2,
    featuresCol="features",
    predictionCol="cluster",
    seed=42
)

# تدريب النموذج
kmeans_model = kmeans.fit(train_data)

# تطبيق النموذج على بيانات الاختبار
clustered_data = kmeans_model.transform(test_data)

# عرض بعض النتائج
clustered_data.select("rating", "review_length", "label", "cluster").show(10)

"""# Analyze Clusters"""

# تحليل كل cluster ومقارنته مع fake/real

from pyspark.sql.functions import count, mean, round

cluster_summary = clustered_data.groupBy("cluster").agg(
    count("*").alias("total_reviews"),
    round(mean("rating"), 2).alias("avg_rating"),
    round(mean("helpful_vote"), 2).alias("avg_helpful_votes"),
    round(mean("review_length"), 2).alias("avg_review_length"),
    round(mean("label"), 2).alias("fake_ratio")
)

cluster_summary.show()

"""# Random Forest"""

from pyspark.ml.classification import RandomForestClassifier

rf = RandomForestClassifier(
    labelCol="label",
    featuresCol="features",
    numTrees=50,
    maxDepth=10,
    seed=42
)

rf_model = rf.fit(train_data)

rf_predictions = rf_model.transform(test_data)

rf_accuracy = accuracy_evaluator.evaluate(rf_predictions)
rf_f1 = f1_evaluator.evaluate(rf_predictions)

print("Random Forest Accuracy:", __builtins__.round(rf_accuracy, 4))
print("Random Forest F1-score:", __builtins__.round(rf_f1, 4))

# Final Model Comparison
# جدول مقارنة نهائي

results = [
    ("Logistic Regression", accuracy, f1_score),
    ("Decision Tree", dt_accuracy, dt_f1),
    ("Naive Bayes", nb_accuracy, nb_f1),
    ("Random Forest", rf_accuracy, rf_f1)
]

results_df = spark.createDataFrame(
    results,
    ["Model", "Accuracy", "F1_score"]
)

results_df.orderBy("Accuracy", ascending=False).show(truncate=False)

"""# Confusion Matrix for Best Model (Decision Tree)"""

# مصفوفة الالتباس لأفضل مودل
# مبدئياً نستخدم Decision Tree لأنه أعطى نتيجة ممتازة

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# إذا Random Forest طلع أفضل، غيري dt_predictions إلى rf_predictions
best_predictions = dt_predictions

# تحويل النتائج إلى Pandas للرسم
y_true = best_predictions.select("label").toPandas()
y_pred = best_predictions.select("prediction").toPandas()

# إنشاء Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(7, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Real Review (0)", "Fake Review (1)"],
    yticklabels=["Real Review (0)", "Fake Review (1)"]
)

plt.title("Confusion Matrix - Best Model")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.show()

# تقرير التصنيف
print(classification_report(
    y_true,
    y_pred,
    target_names=["Real Review", "Fake Review"]
))

"""# Association Rules (FP-Growth)"""

from pyspark.sql.functions import array, col, lit
from pyspark.ml.fpm import FPGrowth
from pyspark.sql.types import StringType

# نحول البيانات إلى "items"
# يجب أن تكون جميع الأعمدة من نفس النوع قبل إنشاء مصفوفة
basket_df = df_clean.withColumn(
    "items",
    array(
        col("verified_purchase").cast(StringType()),
        col("rating").cast(StringType()),
        col("label").cast(StringType())
    )
)

# إنشاء النموذج
fpGrowth = FPGrowth(
    itemsCol="items",
    minSupport=0.2,
    minConfidence=0.6
)

fp_model = fpGrowth.fit(basket_df)

# عرض الأنماط المتكررة
fp_model.freqItemsets.show()

# عرض القوانين
fp_model.associationRules.show()

# 1.0 → Fake Review
# 0.0 → Real Review
# true → Verified Purchase
# 5 → Rating = 5

"""# Live Demonstration: Run Spark Job on New Reviews

"""

from pyspark.sql import Row
from pyspark.sql.functions import length, concat_ws, col

# Create small demo reviews manually
demo_data = [
    Row(
        rating=5.0,
        title="Amazing product",
        text="This product is perfect and I highly recommend it to everyone.",
        helpful_vote=0.0,
        verified_purchase="true"
    ),
    Row(
        rating=1.0,
        title="Bad quality",
        text="The item stopped working after two days and was not worth the money.",
        helpful_vote=3.0,
        verified_purchase="true"
    ),
    Row(
        rating=5.0,
        title="Best purchase ever",
        text="Excellent amazing wonderful product. Everyone should buy it now.",
        helpful_vote=0.0,
        verified_purchase="false"
    )
]

# Convert demo reviews to Spark DataFrame
demo_df = spark.createDataFrame(demo_data)

# Prepare the same features used in training
demo_df = demo_df.withColumn(
    "review_text",
    concat_ws(" ", col("title"), col("text"))
)

demo_df = demo_df.withColumn(
    "review_length",
    length(col("review_text"))
)

# Apply the same NLP pipeline used before
demo_processed = pipeline_model.transform(demo_df)

# Use the best model: Decision Tree
demo_predictions = dt_model.transform(demo_processed)

# Show prediction result
demo_predictions.select(
    "rating",
    "verified_purchase",
    "review_text",
    "prediction",
    "probability"
).show(truncate=False)